### ISSUE TITLE
Disable duration on the styles.css

### ISSUE THREAD

**Issue by Code-Blender-7** [heyitstay11/glitcheffect#1]
### The project itself is awesome. It would be better to disable the durations on the CSS so that the glitch effect doesn't end as long as the mouse is hovering over the text. 
Reference Link - https://codepen.io/jh3y/pen/PoGbxLp

**Comment by heyitstay11** [comment]
Done, Thanks for checking.
![infinite](https://user-images.githubusercontent.com/74863317/109300664-d0c7a000-785c-11eb-98f8-69493e49b09c.PNG)
